server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: reading_record_service_route
          uri: lb://READING-RECORD-SERVICE
          predicates:
            - Method=GET,POST,PUT,DELETE
            - Path=/reading-record/**

        - id: book_service_route
          uri: lb://BOOK-SERVICE
          predicates:
            - Method=GET,POST,PUT,DELETE
            - Path=/book/**

        - id: identity_service_route
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Method=GET,POST,PUT,DELETE
            - Path=/auth/**,/user/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://keycloak.javaguru.by/realms/aprivalov_realm/protocol/openid-connect/certs
