eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8083

spring:
  application:
    name: IDENTITY-SERVICE
  data:
    jdbc:
      dialect: postgresql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  flyway:
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  lifetime: ${JWT_LIFETIME}
